/**
 * Traducao do PrimeVue. Cobre o que aparece nas telas do PayrollOS:
 * DataTable, calendarios e dialogos de confirmacao.
 */
export default {
    startsWith: 'Começa com',
    contains: 'Contém',
    notContains: 'Não contém',
    endsWith: 'Termina com',
    equals: 'Igual a',
    notEquals: 'Diferente de',
    noFilter: 'Sem filtro',
    lt: 'Menor que',
    lte: 'Menor ou igual a',
    gt: 'Maior que',
    gte: 'Maior ou igual a',
    dateIs: 'Data é',
    dateIsNot: 'Data não é',
    dateBefore: 'Data antes de',
    dateAfter: 'Data depois de',
    clear: 'Limpar',
    apply: 'Aplicar',
    matchAll: 'Corresponder a todos',
    matchAny: 'Corresponder a qualquer',
    addRule: 'Adicionar regra',
    removeRule: 'Remover regra',
    accept: 'Sim',
    reject: 'Não',
    choose: 'Escolher',
    upload: 'Enviar',
    cancel: 'Cancelar',
    close: 'Fechar',
    pending: 'Pendente',
    fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB'],
    dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
    dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
    dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
    monthNames: [
        'Janeiro',
        'Fevereiro',
        'Março',
        'Abril',
        'Maio',
        'Junho',
        'Julho',
        'Agosto',
        'Setembro',
        'Outubro',
        'Novembro',
        'Dezembro',
    ],
    monthNamesShort: [
        'Jan',
        'Fev',
        'Mar',
        'Abr',
        'Mai',
        'Jun',
        'Jul',
        'Ago',
        'Set',
        'Out',
        'Nov',
        'Dez',
    ],
    chooseYear: 'Escolher ano',
    chooseMonth: 'Escolher mês',
    chooseDate: 'Escolher data',
    prevDecade: 'Década anterior',
    nextDecade: 'Próxima década',
    prevYear: 'Ano anterior',
    nextYear: 'Próximo ano',
    prevMonth: 'Mês anterior',
    nextMonth: 'Próximo mês',
    prevHour: 'Hora anterior',
    nextHour: 'Próxima hora',
    prevMinute: 'Minuto anterior',
    nextMinute: 'Próximo minuto',
    prevSecond: 'Segundo anterior',
    nextSecond: 'Próximo segundo',
    am: 'am',
    pm: 'pm',
    today: 'Hoje',
    weekHeader: 'Sem',
    firstDayOfWeek: 0,
    dateFormat: 'dd/mm/yy',
    weak: 'Fraca',
    medium: 'Média',
    strong: 'Forte',
    passwordPrompt: 'Digite uma senha',
    emptyFilterMessage: 'Nenhum resultado encontrado',
    searchMessage: '{0} resultados disponíveis',
    selectionMessage: '{0} itens selecionados',
    emptySelectionMessage: 'Nenhum item selecionado',
    emptySearchMessage: 'Nenhum resultado encontrado',
    emptyMessage: 'Nenhum registro encontrado',
    aria: {
        trueLabel: 'Verdadeiro',
        falseLabel: 'Falso',
        nullLabel: 'Não selecionado',
        star: '1 estrela',
        stars: '{star} estrelas',
        selectAll: 'Todos os itens selecionados',
        unselectAll: 'Nenhum item selecionado',
        close: 'Fechar',
        previous: 'Anterior',
        next: 'Próximo',
        navigation: 'Navegação',
        scrollTop: 'Ir para o topo',
        moveTop: 'Mover para o topo',
        moveUp: 'Mover para cima',
        moveDown: 'Mover para baixo',
        moveBottom: 'Mover para o final',
        moveToTarget: 'Mover para o destino',
        moveToSource: 'Mover para a origem',
        moveAllToTarget: 'Mover todos para o destino',
        moveAllToSource: 'Mover todos para a origem',
        pageLabel: 'Página {page}',
        firstPageLabel: 'Primeira página',
        lastPageLabel: 'Última página',
        nextPageLabel: 'Próxima página',
        prevPageLabel: 'Página anterior',
        rowsPerPageLabel: 'Registros por página',
        jumpToPageDropdownLabel: 'Ir para a página',
        jumpToPageInputLabel: 'Ir para a página',
        selectRow: 'Selecionar linha',
        unselectRow: 'Desmarcar linha',
        expandRow: 'Expandir linha',
        collapseRow: 'Recolher linha',
        showFilterMenu: 'Mostrar menu de filtros',
        hideFilterMenu: 'Ocultar menu de filtros',
        filterOperator: 'Operador do filtro',
        filterConstraint: 'Restrição do filtro',
        editRow: 'Editar linha',
        saveEdit: 'Salvar edição',
        cancelEdit: 'Cancelar edição',
        listView: 'Visualização em lista',
        gridView: 'Visualização em grade',
        slide: 'Slide',
        slideNumber: 'Slide {slideNumber}',
        zoomImage: 'Ampliar imagem',
        zoomIn: 'Aproximar',
        zoomOut: 'Afastar',
        rotateRight: 'Girar à direita',
        rotateLeft: 'Girar à esquerda',
    },
};
